user.privileged: root
user.unprivileged: proxy

internal: 0.0.0.0 port = 13370
internal: :: port = 1337

external.protocol: ipv4 ipv6
external: eth0

# pam auth method using file with username:password_hash pairs
# install with this: apt install libpam-pwdfile
# also add this file:
# nano /etc/pam.d/sockd
# with this contentents:
# auth required pam_pwdfile.so pwdfile ${DIR_FOR_PASSWD_FILE}/sockd.passwd
# account required pam_permit.so

socksmethod: pam.username


client pass {
    # allow dual stack (ipv4 + ipv6)
    from: 0/0 to: 0/0


    #per-ip limit
    session.state.key: from
    # total session from single ip
    session.state.max: 200
    # can't create more than 50 concurrent sessions in 1 second
    session.state.throttle: 50/1
    
    # log: connect error
    log: error # Reduced logging for better IO performance
}

socks pass {
    # allow dual stack (ipv4 + ipv6)
    from: 0/0 to: 0/0

    # log: connect disconnect error
    log: error

}
